version: 0.2

env:
  variables:
    DB_USERNAME: admin
    DB_DATABASE: iupeg

  parameter-store:
    DB_PASSWORD: /main/dev/DB_PASSWORD
    DB_HOST: /main/dev/DB_HOST

phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
     - yarn global add serverless --non-interactive --silent
  pre_build:
    commands:
    - composer install --optimize-autoloader --no-dev
    - php artisan migrate --seed
  build:
    commands:
    - serverless deploy

artifacts:
  files:
  - serverless.yml
  - app/**/*
  - bootstrap/**/*
  - config/**/*
  - database/**/*
  - public/**/*
  - resources/**/*
  - routes/**/*
  - scripts/**/*
  - vendor/**/*
  - node_modules/**/*
  - artisan
  - composer.json
  - composer.lock
  - package.json
  - yarn.lock